import { MENU_ITEMS } from '../lib/menu-data.ts';
import { ADD_ONS } from '../lib/order-core.ts';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

// Full price map: base price + optional size prices, mirroring lib/menu-data.ts
// so the Apps Script can recompute totals exactly like the Next.js server.
const priceMap: Record<string, { name: string; price: number; sizes: Record<string, number> | null }> = {};
for (const item of MENU_ITEMS) {
  const sizes: Record<string, number> | null = item.sizes
    ? Object.fromEntries(item.sizes.map((s) => [s.label, s.price]))
    : null;
  priceMap[item.code] = { name: item.name, price: item.price, sizes };
}

const addOnsMap: Record<string, { name: string; price: number }> = {};
for (const a of ADD_ONS) addOnsMap[a.code] = { name: a.name, price: a.price };

const priceMapJson = JSON.stringify(priceMap, null, 2);
const addOnsJson = JSON.stringify(addOnsMap, null, 2);

const gsContent = `
// ============================================================
// Google Apps Script — Orders Webhook
// Auto-generated by _dev/generate-sheets-script.mts
// DO NOT EDIT BY HAND. Re-run the generator after menu changes.
// ============================================================
// Deploy as a web app ("Anyone can send an anonymous request"),
// set the script property GOOGLE_SHEETS_WEBHOOK_TOKEN, share it with the
// sheet owner, then put the web app /exec URL and the token into the
// Next.js .env.local (GOOGLE_SHEETS_WEBHOOK_URL / GOOGLE_SHEETS_WEBHOOK_TOKEN).

var SEEN_ORDERS = {};

var PRICE_MAP = ${priceMapJson};

var ADD_ONS = ${addOnsJson};

var HEADERS = ['Timestamp', 'Order ID', 'Customer Name', 'WhatsApp', 'Table', 'Order Type', 'Items', 'Customizations', 'Special Instructions', 'Subtotal', 'Total', 'Payment Status', 'Order Status'];

function doGet(e) {
  return ContentService.createTextOutput(
    JSON.stringify({ ok: true, message: 'Orders webhook is running' })
  ).setMimeType(ContentService.MimeType.JSON);
}

function doPost(e) {
  try {
    var EXPECTED_TOKEN = PropertiesService.getScriptProperties().getProperty('GOOGLE_SHEETS_WEBHOOK_TOKEN');
    if (!e || !e.postData) {
      return err('Missing request body');
    }
    if (e.postData.type !== 'text/plain') {
      return err('Content-Type must be text/plain');
    }
    var payload = JSON.parse(e.postData.contents);

    if (!payload.token || !EXPECTED_TOKEN || payload.token !== EXPECTED_TOKEN) {
      return err('Invalid token');
    }

    var orderId = String(payload.orderId || '');
    if (!/^ORD-\\d{8}-\\d{6}-[0-9A-F]{4}$/.test(orderId)) {
      return err('Invalid order id');
    }
    var customerName = String(payload.customerName || '').trim();
    if (customerName.length < 2) return err('Customer name is required');
    var whatsappNumber = String(payload.whatsappNumber || '').replace(/\\D/g, '');
    if (!/^[6-9]\\d{9}$/.test(whatsappNumber)) return err('Valid 10-digit mobile number required');

    if (SEEN_ORDERS[orderId]) {
      return ok(orderId, true, null);
    }

    var items = payload.items;
    if (!Array.isArray(items) || items.length === 0) return err('Order has no items');

    var recomputed = 0;
    var hasAddOns = false;
    for (var i = 0; i < items.length; i++) {
      var it = items[i];
      var entry = PRICE_MAP[String(it.code)];
      if (!entry) return err('Unknown item: ' + it.code);
      var qty = Number(it.qty);
      if (!Number.isInteger(qty) || qty < 1 || qty > 50) return err('Invalid quantity for ' + it.code);

      var unit = null;
      if (entry.sizes) {
        var size = String(it.size || '');
        if (!size || entry.sizes[size] === undefined) return err('Invalid size for ' + it.code);
        unit = entry.sizes[size];
      } else {
        if (it.size) return err('Invalid size for ' + it.code);
        unit = entry.price;
      }

      if (Math.round(Number(it.unitPrice)) !== Math.round(unit)) {
        return err('Unit price mismatch for ' + it.code);
      }

      var addTotal = 0;
      var addOns = Array.isArray(it.addOns) ? it.addOns : [];
      for (var j = 0; j < addOns.length; j++) {
        var add = ADD_ONS[String(addOns[j])];
        if (!add) return err('Unknown add-on: ' + addOns[j]);
        addTotal += add.price;
        hasAddOns = true;
      }

      var expectedLine = qty * unit + addTotal;
      if (Math.round(Number(it.lineTotal)) !== Math.round(expectedLine)) {
        return err('Line total mismatch for ' + it.code);
      }
      recomputed += expectedLine;
    }

    if (Math.round(Number(payload.subtotal)) !== Math.round(recomputed)) {
      return err('Subtotal mismatch: sent ' + payload.subtotal + ', expected ' + recomputed);
    }
    if (Math.round(Number(payload.total)) !== Math.round(recomputed)) {
      return err('Total mismatch: sent ' + payload.total + ', expected ' + recomputed);
    }

    SEEN_ORDERS[orderId] = true;

    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('Orders');
    if (!sheet) {
      sheet = ss.insertSheet('Orders');
      sheet.appendRow(HEADERS);
    }

    var customizations = String(payload.customizations || '');
    sheet.appendRow([
      new Date().toISOString(),
      orderId,
      customerName,
      whatsappNumber,
      String(payload.tableNumber || ''),
      String(payload.orderType || 'Dine-in'),
      JSON.stringify(items),
      customizations,
      String(payload.specialInstructions || ''),
      recomputed,
      recomputed,
      String(payload.paymentStatus || 'Pending'),
      String(payload.orderStatus || 'Placed')
    ]);

    return ok(orderId, false, recomputed);
  } catch (err) {
    return err('Server error: ' + (err && err.message ? err.message : String(err)));
  }
}

function ok(orderId, duplicate, serverTotal) {
  var body = { ok: true, orderId: orderId, duplicate: duplicate };
  if (serverTotal !== null) body.serverTotal = serverTotal;
  return ContentService.createTextOutput(JSON.stringify(body)).setMimeType(ContentService.MimeType.JSON);
}

function err(message) {
  return ContentService.createTextOutput(
    JSON.stringify({ ok: false, error: String(message) })
  ).setMimeType(ContentService.MimeType.JSON);
}
`;

const outputPath = path.join(projectRoot, 'docs', 'orders-apps-script.gs.txt');
fs.writeFileSync(outputPath, gsContent.trim(), 'utf-8');
console.log(`Generated Apps Script written to ${outputPath}`);
console.log(`Embedded ${Object.keys(priceMap).length} menu items + ${Object.keys(addOnsMap).length} add-ons in PRICE_MAP/ADD_ONS`);